-- SQLite
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: ibge
DROP TABLE IF EXISTS IBGE;
CREATE TABLE IBGE (Id CHAR (7) PRIMARY KEY ASC NOT NULL, State CHAR (2) NOT NULL, City VARCHAR (80) NOT NULL);

-- Index: IX_IBGE_City
DROP INDEX IF EXISTS IX_IBGE_City;
CREATE INDEX IX_IBGE_City ON IBGE (city ASC);

-- Index: IX_IBGE_State
DROP INDEX IF EXISTS IX_IBGE_State;
CREATE INDEX IX_IBGE_State ON IBGE (state ASC);

-- Index: IX_IBGE_Id
DROP INDEX IF EXISTS IX_IBGE_Id;
CREATE INDEX IX_IBGE_Id ON IBGE (id ASC);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;